openapi: 3.0.0

info:
  title: Simple API
  description: Optional multiline or single-line description
  version: 0.0.1

servers:
  - url: http:/localhost:8080/api/v1
    description: Optional server description

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'


components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string

